"""
Run this script locally once to get a write-scope OAuth token (token_write.json).

This token is used only by set_recording_dates.py and should NEVER be shared
or stored in GitHub Secrets. The CI fetch pipeline uses the separate read-only
token.json generated by login.py.
"""

from pathlib import Path

from google_auth_oauthlib.flow import InstalledAppFlow

SCOPES = ["https://www.googleapis.com/auth/youtube"]

HERE = Path(__file__).parent
CLIENT_SECRET_FILE = HERE / "client_secret.json"
TOKEN_FILE = HERE / "token_write.json"


def main():
    if not CLIENT_SECRET_FILE.exists():
        raise FileNotFoundError(
            f"OAuth client credentials not found: {CLIENT_SECRET_FILE}\n"
            "Download client_secret.json from Google Cloud Console → "
            "APIs & Services → Credentials → OAuth 2.0 Client ID (Desktop app)."
        )

    flow = InstalledAppFlow.from_client_secrets_file(CLIENT_SECRET_FILE, SCOPES)
    creds = flow.run_local_server(port=0)
    TOKEN_FILE.write_text(creds.to_json())

    print(f"Saved credentials to: {TOKEN_FILE}")
    print()
    print("This token has WRITE access to your YouTube account.")
    print("Keep it local — do NOT put it in GitHub Secrets or version control.")
    print()
    print("Use it by running: uv run set_recording_dates.py")


if __name__ == "__main__":
    main()
